package Logic;

import Exceptions.DepartmentExistsInTheList;
import java.util.ArrayList;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Company.java
//  @ Date : 15/05/2018
//  @ Author : 
//
//




public class Company {
    public ArrayList<Department> depList = new ArrayList<Department>();        
    public Company() {
        
    }
    
    public void addDep(String loc, String name) throws DepartmentExistsInTheList {
        //declare found and set to false.
        boolean found = false;
        
        // loop used for checking if department already exists in the depList
        for (int i = 0; i < depList.size() && !found; i++) {
            
            //Deplist is not empty
            if (depList.size() > 0) {
                // find if passed values are the same in the list.
                if (loc.equalsIgnoreCase(depList.get(i).getLocation())
                && name.equalsIgnoreCase(depList.get(i).getName())) {
                    
                    found = true; //duplication found, set found to true.
                    throw new DepartmentExistsInTheList("Department"
                            + " already exists."); // throw exception
                }
            }  
        }
        // if duplication was not found or the size is 0
        if (found == false || depList.size() == 0) {
            //create new dep object and pass name and loc through custom constructor
            Department dep = new Department(name, loc);
            depList.add(dep); // add dep object to depList
        }
    }
        
	
    public void addEmp(String firstName, String surname, char gender, 
            int payLevel, String address, int depid) {
	//Create an emplpoyee object
        Employee emp = new Employee(firstName, surname, gender,
                payLevel, address);
        
        for (int i = 0; i < 10; i++) {
            
        }
        depList.get(i).getDepid() =
        
        
    }
	
    public void deleteEmp() {
	
    }
	
    public void deleteDep() {
	
    }
	
    public void alterEmpDetails() {
	
    }
	
    public void alterDepDetails() {
	
    }
	
    public void assignEmpToDep() {
	
    }
	
    public void setEmpToDep() {
	
    }
    
    public void setEmpAsDepHead() {
	
    }
	
    public void listEmployeesInDep() {
	
    }
	
    public void producePayReport() {
	
    }

    public ArrayList<Department> getDepList() {
        return depList;
    }

    
	
	
}
