package Logic;

import Logic.Employee;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.java
//  @ Date : 15/05/2018
//  @ Author : 
//
//

public class Department {
    private String name;
    private String location;
    private int depid;
    private static int depidCounter = 10;
    public ArrayList<Employee> empList = new ArrayList<Employee>();;

    public Department(String name, String location) {
        this.name = name;
        this.location = location;
        this.depid = this.depidCounter++;  
    }

    public String getName() {
        return this.name;          
    }
	
    public String getLocation() {
	return this.location;
    }
	
    public int getDepid() {
	return this.depid;
    }
	
    public void setName(String aName) {
        this.name = aName;
    }
	
    public void setLocation(String aLocation) {
        this.location = aLocation;
    }

    public ArrayList<Employee> getEmpList() {
        return empList;
    }

    @Override
    public String toString() {
        return depid + ", " + name + ", " +location; 
    }
    
    
	
}
