package Logic;


//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Employee.java
//  @ Date : 15/05/2018
//  @ Author : 
//
//




public class Employee {
    private String firstName;
    private String surname;
    private char gender;
    private int empid;
    private static int empidCounter = 1000;
    private int payLevel;
    private String address;
    private boolean headOfDep;

    public Employee(String firstName, String surname, char gender, 
            int payLevel, String address) {
        this.firstName = firstName;
        this.surname = surname;
        this.gender = gender;
        this.empid = empidCounter++;
        this.payLevel = payLevel;
        this.address = address;
        this.headOfDep = false;
    }
    
    
	
    public String getFirstName() {
        return this.firstName;
    }
	
    public String getSurname() {
	return this.surname;
    }
	
    public char getGender() {
	return this.gender;
    }
	
    public int getEmpid() {
	return this.empid;
    }
	
    public String getAddress() {
	return this.address;
    }
    public boolean getHeadOfDep() {
        return this.headOfDep;
    }

    public void setHeadOfDep(boolean headOfDep) {
        this.headOfDep = headOfDep;
    }
    
    public int getPayLevel() {
	return this.payLevel;
    }
    
    public void setFirstName(String afirstName) {
	this.firstName = afirstName;
    }
	
    public void setSurname(String aSurname) {
	this.surname = aSurname;
    }
	
    public void setGender(char aGender) {
	this.gender = aGender;
    }
	
    public void setAddress(String aAddress) {
	this.address = aAddress;
    }
	
    public void setPayLevel(int apayLevel) {
	this.payLevel = apayLevel;
    }
}
