/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Company;

/**
 *
 * @author malakreyadh
 */
public class MainMenu extends javax.swing.JFrame {
    
    /* Declare a Company class object.
       This object should only be created once in the main menu.
       Reason: there should only be one company with many departments.
     */
    private static Company comp = new Company();
   
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Footer = new javax.swing.JPanel();
        jBtnSave = new javax.swing.JButton();
        jBtnGenRep = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        Title = new javax.swing.JPanel();
        jTitle = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBtnAddDep = new javax.swing.JButton();
        jBtnAddEmp = new javax.swing.JButton();
        jBtnEditDepInfo = new javax.swing.JButton();
        jBtnEditEmpInfo = new javax.swing.JButton();
        jBtnAssignEmpToDep = new javax.swing.JButton();
        jBtnAssignHeadToDep = new javax.swing.JButton();
        jBtnDelDep = new javax.swing.JButton();
        jBtnDelEmp = new javax.swing.JButton();
        jBtnListEmpofDep = new javax.swing.JButton();
        jBtnNewInstall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Human Resources Administion System");

        Footer.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });
        Footer.add(jBtnSave);

        jBtnGenRep.setText("Generate Report");
        Footer.add(jBtnGenRep);

        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        Footer.add(jBtnExit);

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        Title.setLayout(new java.awt.BorderLayout());

        jTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jTitle.setForeground(new java.awt.Color(51, 153, 255));
        jTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitle.setText("Main Menu");
        Title.add(jTitle, java.awt.BorderLayout.CENTER);

        getContentPane().add(Title, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnAddDep.setText("Add a New Department");
        jBtnAddDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddDepActionPerformed(evt);
            }
        });

        jBtnAddEmp.setText("Add a New Employee");
        jBtnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddEmpActionPerformed(evt);
            }
        });

        jBtnEditDepInfo.setText("Edit Department Information");
        jBtnEditDepInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditDepInfoActionPerformed(evt);
            }
        });

        jBtnEditEmpInfo.setText("Edit Employee Information");
        jBtnEditEmpInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditEmpInfoActionPerformed(evt);
            }
        });

        jBtnAssignEmpToDep.setText("Assign Employee To Department");
        jBtnAssignEmpToDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAssignEmpToDepActionPerformed(evt);
            }
        });

        jBtnAssignHeadToDep.setText("Assign Head To Department");
        jBtnAssignHeadToDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAssignHeadToDepActionPerformed(evt);
            }
        });

        jBtnDelDep.setText("Delete a Department");
        jBtnDelDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelDepActionPerformed(evt);
            }
        });

        jBtnDelEmp.setText("Delete an Employee");
        jBtnDelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelEmpActionPerformed(evt);
            }
        });

        jBtnListEmpofDep.setText("List Employees of a Department");
        jBtnListEmpofDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListEmpofDepActionPerformed(evt);
            }
        });

        jBtnNewInstall.setText("New Installation");
        jBtnNewInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewInstallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnAssignEmpToDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEditDepInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEditEmpInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAddEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAddDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAssignHeadToDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnDelDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnDelEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnListEmpofDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnNewInstall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBtnAddDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAddEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEditDepInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEditEmpInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAssignEmpToDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAssignHeadToDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDelDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDelEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnListEmpofDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnNewInstall))
        );

        Main.add(jPanel1);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnAddDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddDepActionPerformed
        new NewDepFrame().setVisible(true); //instantiate frame and set visible to true
        this.setVisible(false); //turn mainmenu frame off.
    }//GEN-LAST:event_jBtnAddDepActionPerformed

    private void jBtnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddEmpActionPerformed
        new NewEmpFrame().setVisible(true); //instantiate frame and set visible to true
        this.setVisible(false); //turn mainmenu frame off.
    }//GEN-LAST:event_jBtnAddEmpActionPerformed

    private void jBtnEditDepInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditDepInfoActionPerformed
        new EditDepFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnEditDepInfoActionPerformed

    private void jBtnEditEmpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditEmpInfoActionPerformed
        new EditEmpFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnEditEmpInfoActionPerformed

    private void jBtnAssignEmpToDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAssignEmpToDepActionPerformed
        new AssignEmpToDepFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnAssignEmpToDepActionPerformed

    private void jBtnAssignHeadToDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAssignHeadToDepActionPerformed
        new AssignHeadToDepFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnAssignHeadToDepActionPerformed

    private void jBtnDelDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelDepActionPerformed
        new DelDepFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnDelDepActionPerformed

    private void jBtnDelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelEmpActionPerformed
        new DelEmpFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnDelEmpActionPerformed

    private void jBtnListEmpofDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListEmpofDepActionPerformed
        new ListEmpDepFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnListEmpofDepActionPerformed

    private void jBtnNewInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewInstallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNewInstallActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }
    public Company getCompany(){
        return this.comp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Title;
    private javax.swing.JButton jBtnAddDep;
    private javax.swing.JButton jBtnAddEmp;
    private javax.swing.JButton jBtnAssignEmpToDep;
    private javax.swing.JButton jBtnAssignHeadToDep;
    private javax.swing.JButton jBtnDelDep;
    private javax.swing.JButton jBtnDelEmp;
    private javax.swing.JButton jBtnEditDepInfo;
    private javax.swing.JButton jBtnEditEmpInfo;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnGenRep;
    private javax.swing.JButton jBtnListEmpofDep;
    private javax.swing.JButton jBtnNewInstall;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables

    
}
