package GUI;

import Exceptions.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malakreyadh
 */
public class NewEmpFrame extends javax.swing.JFrame {
    private MainMenu main = new MainMenu();
    /**
     * Creates new form NewEmpFrame
     */
    public NewEmpFrame() {
        initComponents();
        
        for (int i = 0; i < main.getCompany().getDepList().size(); i++) {
            
            jComboBoxDepId.addItem(Integer.toString(main.getCompany()
                    .getDepList().get(i).getDepid()));
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGrp = new javax.swing.ButtonGroup();
        Footer = new javax.swing.JPanel();
        jBtnCreate = new javax.swing.JButton();
        jBtnReturn = new javax.swing.JButton();
        Main = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtFirstName = new javax.swing.JTextField();
        jTxtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadBtnMale = new javax.swing.JRadioButton();
        jRadBtnFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTxtPayScale = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDepId = new javax.swing.JComboBox<>();
        Title = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Footer.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

        jBtnCreate.setText("Create");
        jBtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreateActionPerformed(evt);
            }
        });
        Footer.add(jBtnCreate);

        jBtnReturn.setText("Return To Main Menu");
        jBtnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReturnActionPerformed(evt);
            }
        });
        Footer.add(jBtnReturn);

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("First Name:");

        jLabel3.setText("Surname:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Address:");

        genderBtnGrp.add(jRadBtnMale);
        jRadBtnMale.setText("Male");

        genderBtnGrp.add(jRadBtnFemale);
        jRadBtnFemale.setText("Female");

        jLabel6.setText("Pay Scale:");

        jLabel1.setText("Department ID:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtSurname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadBtnMale)
                                .addGap(79, 79, 79)
                                .addComponent(jRadBtnFemale))
                            .addComponent(jTxtFirstName)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPayScale)
                            .addComponent(jComboBoxDepId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtAddress, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadBtnMale)
                    .addComponent(jRadBtnFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtPayScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxDepId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        jLblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitle.setText("Add New Employee");
        Title.add(jLblTitle);

        getContentPane().add(Title, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReturnActionPerformed
        new MainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnReturnActionPerformed

    private void jBtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreateActionPerformed
        //declare varaibles
        String address = null, firstname = null,  surname = null;
        int payscale = 0;
        int depid = 0;
        char gender = ' ';
        
        try {
            //getting the text from the textboxes and storing in the varaibles
            address = jTxtAddress.getText();

            firstname = jTxtFirstName.getText();

            payscale = Integer.parseInt(jTxtPayScale.getText());
            ;
            
            surname = jTxtSurname.getText();

            depid = Integer.parseInt((String)jComboBoxDepId.getSelectedItem());
            
            if(payscale <1 || payscale >7 ){
                
                throw new Exception("Please a number from 1 to 7.");
            }
                
            if (jRadBtnFemale.isSelected()) {
                gender = 'F';

            } else if (jRadBtnMale.isSelected()) {
                gender = 'M';
            }  else if (!jRadBtnFemale.isSelected() || !jRadBtnMale.isSelected()) {
                
                throw new TextFieldEmptyException("Text Field is empty."
                      + "\nPlease select a gender.");
            
            }
            
            if (address.isEmpty() || firstname.isEmpty() ||
                surname.isEmpty()){
                
                
                throw new TextFieldEmptyException("Text Field is empty."
                      + "\nPlease enter all the details to create Employee.");
                
            }
            
            /*Invoking the getCompany method which returns Company class
            object in order to invoke the addDep method of that object */
            payscale = Integer.parseInt(jTxtPayScale.getText());
            main.getCompany().addEmp(firstname,surname,gender,payscale,address, depid); // passing loc and name values
            
            //Showing the user a message of confirmation
            JOptionPane.showMessageDialog(null, "Employee added."); 
            
        } 
        
        catch(TextFieldEmptyException xe){
        
            JOptionPane.showMessageDialog(null, xe, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        catch(NumberFormatException xe){
            
            JOptionPane.showMessageDialog(null, xe, "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception xe){
            
            JOptionPane.showMessageDialog(null, xe, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Title;
    private javax.swing.ButtonGroup genderBtnGrp;
    private javax.swing.JButton jBtnCreate;
    private javax.swing.JButton jBtnReturn;
    private javax.swing.JComboBox<String> jComboBoxDepId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadBtnFemale;
    private javax.swing.JRadioButton jRadBtnMale;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtPayScale;
    private javax.swing.JTextField jTxtSurname;
    // End of variables declaration//GEN-END:variables
}
